backend:
  name: github
  repo: jack-gannon/Personal-Site

media_folder: static/assets
public_folder: assets
media_library:
  {
    name: cloudinary,
    config: { cloud_name: dthoxmity, api_key: 144732167219663 },
  }

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: author, label: Author, default: "Jack Gannon" }
      - { name: description, label: Description }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: content/portfolio
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: thumbnail, label: Featured Image, widget: image }
      - {
          name: project-images,
          label: Project Images,
          widget: image,
          media_library: { config: { multiple: true } },
        }
      - { name: body, label: Body, widget: markdown }
