backend:
  name: github
  repo: jack-gannon/Personal-Site

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: content_type, label: Content Type, default: Blog Post }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: author, label: Author, default: "Jack Gannon" }
      - { name: category, label: Category, widget: select, options: ["Personal", "Design", "Development"] }
      - { name: tags, label: Tags, widget: list }
      - { name: description, label: Description }
      - {
          name: thumbnail,
          label: Featured Image,
          widget: object,
          fields:
            - {
              label: Image,
              name: image,
              widget: image,
              default: ../assets/placeholder.png,
            },
          - { label: Alt Text, name: alt_text, widget: String }
        }
      - { name: body, label: Body, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: content/portfolio
    create: true
    fields:
      - { name: path, label: Path }
      - { name: content_type, label: Content Type, default: Portfolio Project }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: thumbnail, label: Featured Image, widget: image }
      - {
          name: project-images,
          label: Project Images,
          widget: list,
          fields: 
            - { label: Image, name: image, widget: image }
            - { label: Alt Text, name: alt_text, widget: string }
        }
      # - {
      #     name: project-images,
      #     label: Project Images,
      #     widget: image,
      #     media_library:
      #       {
      #         name: cloudinary,
      #         config: { cloud_name: dthoxmity, api_key: 144732167219663 },
      #       },
      #   }
      - { name: body, label: Body, widget: markdown }
