backend:
  name: github
  repo: jack-gannon/Personal-Site

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - {
          name: content_type,
          label: Content Type,
          widget: hidden,
          default: Blog Post,
        }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: author, label: Author, default: "Jack Gannon" }
      - { name: category, label: Category }
      - { name: tags, label: Tags, widget: list, default: ["Jack Gannon"] }
      - { name: description, label: Description }
      - name: thumbnail
        label: Featured Image
        widget: object
        fields:
          - {
              name: image,
              label: Image,
              widget: image,
              default: ../assets/placeholder.png,
            }
          - { name: alt_text, label: Alt Text, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: content/portfolio
    create: true
    fields:
      - { name: path, label: Path }
      - {
          name: content_type,
          label: Content Type,
          widget: hidden,
          default: Portfolio Project,
        }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: thumbnail, label: Featured Image, widget: image }
      - name: project_images
        label: Project Images
        widget: list
        fields:
          - { name: project_image, label: Project Image, widget: image }
          - { name: alt_text, label: Alt Text, widget: string }
      - name: tools
        label: Tools
        widget: select
        multiple: true
        options:
          - label: React
            value:
              - name: React
                label: React
                logo: ../assets/logos/react.svg
                widget: object
                fields:
                  - { label: Description, name: description, widget: string }

      - { name: body, label: Body, widget: markdown }
